version: "3.8"

services:
  api:
    build: .
    restart: always
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    ports:
      - "8001:8000"